ALTER TABLE users ADD COLUMN profile_pictue VARCHAR(255);
ALTER TABLE users MODIFY COLUMN email VARCHAR(320);

ALTER TABLE posts ADD COLUMN title VARCHAR(255);
ALTER TABLE posts MODIFY COLUMN content LONGTEXT;